2021-07-22 06:09:56,005 DEBUG    root            Loaded Command Group: ['gcloud', 'ai_platform']
2021-07-22 06:09:56,007 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local']
2021-07-22 06:09:56,009 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local', 'predict']
2021-07-22 06:09:56,015 DEBUG    root            Running [gcloud.ai-platform.local.predict] with arguments: [--model-dir: "output/keras_export/", --text-instances: "./test.csv"]
2021-07-22 06:09:56,015 INFO     ___FILE_ONLY___ If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.

2021-07-22 06:09:58,861 DEBUG    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-22 06:09:58.229317: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-22 06:09:58.319684: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200215000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\nERROR:root:Exception running the graph.\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 259, in predict\n    preprocessed, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 391, in predict\n    "Exception during running the graph: " + str(e))\ncloud.ml.prediction.prediction_utils.PredictionError: Failed to run the provided model: Exception during running the graph: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\' (Error code: 2)\n'
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/local/predict.py", line 100, in Run
    signature_name=args.signature_name)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_utils.py", line 112, in RunPredict
    raise LocalPredictRuntimeError(err)
googlecloudsdk.command_lib.ml_engine.local_utils.LocalPredictRuntimeError: b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-22 06:09:58.229317: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-22 06:09:58.319684: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200215000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\nERROR:root:Exception running the graph.\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 259, in predict\n    preprocessed, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 391, in predict\n    "Exception during running the graph: " + str(e))\ncloud.ml.prediction.prediction_utils.PredictionError: Failed to run the provided model: Exception during running the graph: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\' (Error code: 2)\n'
2021-07-22 06:09:58,863 ERROR    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-22 06:09:58.229317: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-22 06:09:58.319684: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200215000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\nERROR:root:Exception running the graph.\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 387, in predict\n    outputs = self._session.run(fetches=fetches, feed_dict=unaliased)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run\n    run_metadata_ptr)\n  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1160, in _run\n    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)\n  File "/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 259, in predict\n    preprocessed, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 391, in predict\n    "Exception during running the graph: " + str(e))\ncloud.ml.prediction.prediction_utils.PredictionError: Failed to run the provided model: Exception during running the graph: could not convert string to float: \'0.3906662166118622,0.0,-0.03031095676124096,0.0,0.0,4.0,2.0,-0.14480669796466827,-0.2171185314655304,-0.034042954444885254,38.0\' (Error code: 2)\n'
