2021-07-22 06:41:51,403 DEBUG    root            Loaded Command Group: ['gcloud', 'ai_platform']
2021-07-22 06:41:51,406 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs']
2021-07-22 06:41:51,408 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs', 'submit']
2021-07-22 06:41:51,429 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs', 'submit', 'training']
2021-07-22 06:41:51,472 DEBUG    root            Running [gcloud.ai-platform.jobs.submit.training] with arguments: [--job-dir: "<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7fdaf2c3c950>", --module-name: "trainer.task", --package-path: "trainer/", --python-version: "3.7", --region: "us-central1", --runtime-version: "2.5", JOB: "census_210722_064150"]
2021-07-22 06:41:51,491 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:41:51,495 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:41:51,496 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:41:51,497 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:41:51,500 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 249
2021-07-22 06:41:51,515 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:41:51,517 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:41:51,519 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:41:51,520 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:41:51,522 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 249
2021-07-22 06:41:51,529 DEBUG    root            Looking for setup.py file at [/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py]
2021-07-22 06:41:51,529 INFO     root            Generating temporary setup.py file:
from setuptools import setup, find_packages

if __name__ == '__main__':
    setup(
        name='trainer',
        packages=find_packages(include=['trainer'])
    )

2021-07-22 06:41:51,530 DEBUG    root            Executing command: ['/opt/conda/bin/python3', '-S', '/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py', 'egg_info', '--egg-base', '/tmp/tmpvmgvh49g', 'build', '--build-base', '/tmp/tmpvmgvh49g', '--build-temp', '/tmp/tmpvmgvh49g', 'sdist', '--dist-dir', '/tmp/tmphxdtujn9/output']
2021-07-22 06:41:51,817 DEBUG    root            Executing command: ['/opt/conda/bin/python3', '/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py', 'egg_info', '--egg-base', '/tmp/tmpvmgvh49g', 'build', '--build-base', '/tmp/tmpvmgvh49g', '--build-temp', '/tmp/tmpvmgvh49g', 'sdist', '--dist-dir', '/tmp/tmphxdtujn9/output']
2021-07-22 06:41:52,344 DEBUG    root            Python packaging resulted in [/tmp/tmphxdtujn9/output/trainer-0.0.0.tar.gz]
2021-07-22 06:41:52,345 DEBUG    root            Couldn't remove file [/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.pyc] (it may never have been created).
2021-07-22 06:41:52,353 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:41:52,356 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:41:52,357 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:41:52,358 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:41:52,361 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:41:52,368 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:41:52,370 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:41:52,371 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:41:52,372 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:41:52,375 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:41:52,399 INFO     root            Uploading [/tmp/tmphxdtujn9/output/trainer-0.0.0.tar.gz] to [ultra-evening-318614-aiplatform/census_210722_064150/packages/44e2ab5f4078cda941633931b00ce9a2c5b84b19cfa1e510e54780342da82d6b/trainer-0.0.0.tar.gz]
2021-07-22 06:41:52,406 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): storage.googleapis.com:443
2021-07-22 06:41:52,528 DEBUG    urllib3.connectionpool https://storage.googleapis.com:443 "POST /upload/storage/v1/b/ultra-evening-318614-aiplatform/o?alt=json&name=census_210722_064150%2Fpackages%2F44e2ab5f4078cda941633931b00ce9a2c5b84b19cfa1e510e54780342da82d6b%2Ftrainer-0.0.0.tar.gz&uploadType=multipart HTTP/1.1" 200 1246
2021-07-22 06:41:52,532 DEBUG    root            Using ['gs://ultra-evening-318614-aiplatform/census_210722_064150/packages/44e2ab5f4078cda941633931b00ce9a2c5b84b19cfa1e510e54780342da82d6b/trainer-0.0.0.tar.gz'] as trainer uris
2021-07-22 06:41:52,539 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): ml.googleapis.com:443
2021-07-22 06:41:52,808 DEBUG    urllib3.connectionpool https://ml.googleapis.com:443 "POST /v1/projects/ultra-evening-318614/jobs?alt=json HTTP/1.1" 403 None
2021-07-22 06:41:52,824 DEBUG    root            (gcloud.ai-platform.jobs.submit.training) User [114789316337-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-evening-318614] (or it may not exist): AI Platform Training & Prediction API has not been used in project 114789316337 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/114789316337
    service: ml.googleapis.com
  reason: SERVICE_DISABLED
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/jobs/submit/training.py", line 122, in Run
    custom_train_server_config=custom_container_config)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/jobs_util.py", line 416, in SubmitTraining
    job = jobs_client.Create(project_ref, job)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/ml_engine/jobs.py", line 93, in Create
    job=job))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/ml/v1/ml_v1_client.py", line 100, in Create
    config, request, global_params=global_params)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 735, in _RunMethod
    http, http_request, **opts)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 360, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 350, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 406, in _MakeRequestNoRetry
    check_response_func(response)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 242, in _CheckResponseForApiEnablement
    PromptToEnableApi(*enablement_info)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 209, in PromptToEnableApi
    raise exception
googlecloudsdk.api_lib.util.exceptions.HttpException: User [114789316337-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-evening-318614] (or it may not exist): AI Platform Training & Prediction API has not been used in project 114789316337 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/114789316337
    service: ml.googleapis.com
  reason: SERVICE_DISABLED
2021-07-22 06:41:52,830 ERROR    root            (gcloud.ai-platform.jobs.submit.training) User [114789316337-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-evening-318614] (or it may not exist): AI Platform Training & Prediction API has not been used in project 114789316337 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/ml.googleapis.com/overview?project=114789316337
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/114789316337
    service: ml.googleapis.com
  reason: SERVICE_DISABLED
