2021-07-22 06:44:43,406 DEBUG    root            Loaded Command Group: ['gcloud', 'ai_platform']
2021-07-22 06:44:43,409 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs']
2021-07-22 06:44:43,411 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs', 'submit']
2021-07-22 06:44:43,432 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'jobs', 'submit', 'training']
2021-07-22 06:44:43,477 DEBUG    root            Running [gcloud.ai-platform.jobs.submit.training] with arguments: [--job-dir: "<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7f78a24c7a50>", --module-name: "trainer.task", --package-path: "trainer/", --python-version: "3.7", --region: "us-central1", --runtime-version: "2.5", JOB: "census_210722_064442"]
2021-07-22 06:44:43,495 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:44:43,499 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:44:43,501 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:44:43,502 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:44:43,506 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:44:43,520 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:44:43,523 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:44:43,525 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:44:43,526 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:44:43,529 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:44:43,537 DEBUG    root            Looking for setup.py file at [/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py]
2021-07-22 06:44:43,537 INFO     root            Generating temporary setup.py file:
from setuptools import setup, find_packages

if __name__ == '__main__':
    setup(
        name='trainer',
        packages=find_packages(include=['trainer'])
    )

2021-07-22 06:44:43,538 DEBUG    root            Executing command: ['/opt/conda/bin/python3', '-S', '/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py', 'egg_info', '--egg-base', '/tmp/tmpsp082aqu', 'build', '--build-base', '/tmp/tmpsp082aqu', '--build-temp', '/tmp/tmpsp082aqu', 'sdist', '--dist-dir', '/tmp/tmpwg23ubsn/output']
2021-07-22 06:44:43,867 DEBUG    root            Executing command: ['/opt/conda/bin/python3', '/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.py', 'egg_info', '--egg-base', '/tmp/tmpsp082aqu', 'build', '--build-base', '/tmp/tmpsp082aqu', '--build-temp', '/tmp/tmpsp082aqu', 'sdist', '--dist-dir', '/tmp/tmpwg23ubsn/output']
2021-07-22 06:44:44,394 DEBUG    root            Python packaging resulted in [/tmp/tmpwg23ubsn/output/trainer-0.0.0.tar.gz]
2021-07-22 06:44:44,394 DEBUG    root            Couldn't remove file [/home/jupyter/training-data-analyst/self-paced-labs/ai-platform-qwikstart/setup.pyc] (it may never have been created).
2021-07-22 06:44:44,402 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:44:44,405 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:44:44,407 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:44:44,408 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:44:44,411 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:44:44,419 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true
2021-07-22 06:44:44,421 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-07-22 06:44:44,423 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2021-07-22 06:44:44,423 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token
2021-07-22 06:44:44,426 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/114789316337-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 250
2021-07-22 06:44:44,450 INFO     root            Uploading [/tmp/tmpwg23ubsn/output/trainer-0.0.0.tar.gz] to [ultra-evening-318614-aiplatform/census_210722_064442/packages/1b2bd9639e927a489db1f2079ae91afa3038c80b8007c057d80219f328e25ca2/trainer-0.0.0.tar.gz]
2021-07-22 06:44:44,457 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): storage.googleapis.com:443
2021-07-22 06:44:44,569 DEBUG    urllib3.connectionpool https://storage.googleapis.com:443 "POST /upload/storage/v1/b/ultra-evening-318614-aiplatform/o?alt=json&name=census_210722_064442%2Fpackages%2F1b2bd9639e927a489db1f2079ae91afa3038c80b8007c057d80219f328e25ca2%2Ftrainer-0.0.0.tar.gz&uploadType=multipart HTTP/1.1" 200 1246
2021-07-22 06:44:44,573 DEBUG    root            Using ['gs://ultra-evening-318614-aiplatform/census_210722_064442/packages/1b2bd9639e927a489db1f2079ae91afa3038c80b8007c057d80219f328e25ca2/trainer-0.0.0.tar.gz'] as trainer uris
2021-07-22 06:44:44,580 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): ml.googleapis.com:443
2021-07-22 06:44:56,995 DEBUG    urllib3.connectionpool https://ml.googleapis.com:443 "POST /v1/projects/ultra-evening-318614/jobs?alt=json HTTP/1.1" 400 None
2021-07-22 06:44:57,003 DEBUG    root            (gcloud.ai-platform.jobs.submit.training) INVALID_ARGUMENT: Field: runtime_version Error: The specified runtime version '2.5' with the Python version '3.7' is not supported or is deprecated. Please specify a different runtime version. See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list of supported versions.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: The specified runtime version '2.5' with the Python version '3.7'
      is not supported or is deprecated. Please specify a different runtime version.
      See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list
      of supported versions.
    field: runtime_version
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/jobs/submit/training.py", line 122, in Run
    custom_train_server_config=custom_container_config)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/jobs_util.py", line 416, in SubmitTraining
    job = jobs_client.Create(project_ref, job)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/ml_engine/jobs.py", line 93, in Create
    job=job))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/ml/v1/ml_v1_client.py", line 100, in Create
    config, request, global_params=global_params)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 610, in __ProcessHttpResponse
    http_response, method_config=method_config, request=request)
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://ml.googleapis.com/v1/projects/ultra-evening-318614/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Thu, 22 Jul 2021 06:44:56 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 400}>, content <{
  "error": {
    "code": 400,
    "message": "Field: runtime_version Error: The specified runtime version '2.5' with the Python version '3.7' is not supported or is deprecated. Please specify a different runtime version. See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list of supported versions.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "runtime_version",
            "description": "The specified runtime version '2.5' with the Python version '3.7' is not supported or is deprecated. Please specify a different runtime version. See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list of supported versions."
          }
        ]
      }
    ]
  }
}
>
2021-07-22 06:44:57,004 ERROR    root            (gcloud.ai-platform.jobs.submit.training) INVALID_ARGUMENT: Field: runtime_version Error: The specified runtime version '2.5' with the Python version '3.7' is not supported or is deprecated. Please specify a different runtime version. See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list of supported versions.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: The specified runtime version '2.5' with the Python version '3.7'
      is not supported or is deprecated. Please specify a different runtime version.
      See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list
      of supported versions.
    field: runtime_version
