2021-07-26 17:11:34,652 DEBUG    root            Loaded Command Group: ['gcloud', 'ai_platform']
2021-07-26 17:11:34,654 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local']
2021-07-26 17:11:34,656 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local', 'predict']
2021-07-26 17:11:34,662 DEBUG    root            Running [gcloud.ai-platform.local.predict] with arguments: [--json-instances: "x_input.json", --model-dir: "output"]
2021-07-26 17:11:34,663 INFO     ___FILE_ONLY___ If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.

2021-07-26 17:11:37,141 DEBUG    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:11:36.608946: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:11:36.645072: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[2.15335703 -0.0584124178 0.0687887296 ... -0.678862929 -0.0214707926 -0.864984453]\n [-0.187132627 -1.36801565 2.46972942 ... 2.07550645 0.778948545 0.104453072]\n [-0.826865375 -0.0871616825 0.846812427 ... -0.0110387336 0.0710852593 -0.340856403]\n ...\n [0.493288755 0.697273076 -0.271910191 ... 0.701913416 1.52339756 0.367529541]\n [0.206744522 -0.1996876 -0.00432538707 ... -0.209038675 0.493010163 -0.0161018763]\n [1.54266655 0.920600891 -2.04845428 ... 0.973365605 0.825092852 -1.04977798]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/local/predict.py", line 100, in Run
    signature_name=args.signature_name)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_utils.py", line 112, in RunPredict
    raise LocalPredictRuntimeError(err)
googlecloudsdk.command_lib.ml_engine.local_utils.LocalPredictRuntimeError: b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:11:36.608946: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:11:36.645072: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[2.15335703 -0.0584124178 0.0687887296 ... -0.678862929 -0.0214707926 -0.864984453]\n [-0.187132627 -1.36801565 2.46972942 ... 2.07550645 0.778948545 0.104453072]\n [-0.826865375 -0.0871616825 0.846812427 ... -0.0110387336 0.0710852593 -0.340856403]\n ...\n [0.493288755 0.697273076 -0.271910191 ... 0.701913416 1.52339756 0.367529541]\n [0.206744522 -0.1996876 -0.00432538707 ... -0.209038675 0.493010163 -0.0161018763]\n [1.54266655 0.920600891 -2.04845428 ... 0.973365605 0.825092852 -1.04977798]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
2021-07-26 17:11:37,142 ERROR    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:11:36.608946: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:11:36.645072: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[2.15335703 -0.0584124178 0.0687887296 ... -0.678862929 -0.0214707926 -0.864984453]\n [-0.187132627 -1.36801565 2.46972942 ... 2.07550645 0.778948545 0.104453072]\n [-0.826865375 -0.0871616825 0.846812427 ... -0.0110387336 0.0710852593 -0.340856403]\n ...\n [0.493288755 0.697273076 -0.271910191 ... 0.701913416 1.52339756 0.367529541]\n [0.206744522 -0.1996876 -0.00432538707 ... -0.209038675 0.493010163 -0.0161018763]\n [1.54266655 0.920600891 -2.04845428 ... 0.973365605 0.825092852 -1.04977798]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
